# Generated by Django 4.2.2 on 2023-07-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFa', '0002_alter_newsandarticles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عکس گالری', max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='gallery_images', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عکس گالری',
                'verbose_name_plural': 'عکس های گالری',
            },
        ),
    ]
