# Generated by Django 4.2.2 on 2023-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFa', '0003_galleryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='description',
            field=models.CharField(default='توضیحات عکس', max_length=150, verbose_name='توضیحات'),
        ),
    ]
