# Generated by Django 4.2.2 on 2023-07-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFa', '0004_galleryimages_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='پلن', max_length=150, verbose_name='عنوان پلن')),
                ('image', models.ImageField(upload_to='plans', verbose_name='عکس')),
                ('description', models.CharField(default='توضیحات پلن', max_length=150, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن ها',
            },
        ),
    ]
