# Generated by Django 4.2.2 on 2023-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFa', '0005_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'پلان', 'verbose_name_plural': 'پلان ها'},
        ),
        migrations.AlterField(
            model_name='plans',
            name='description',
            field=models.CharField(default='توضیحات پلان', max_length=150, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='title',
            field=models.CharField(default='پلان', max_length=150, verbose_name='عنوان پلان'),
        ),
    ]
