# Generated by Django 4.2.2 on 2023-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreFa', '0006_alter_plans_options_alter_plans_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='is_rendered',
            field=models.BooleanField(default=False, verbose_name='رندر است؟'),
        ),
    ]
