# Generated by Django 4.2.2 on 2023-07-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreFa', '0007_galleryimages_is_rendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimages',
            name='is_rendered',
        ),
    ]
